version: 2
jobs:
  build:
    working_directory: ~/mirageframework
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install

    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
